version: "3.8"
services:
  web:
    build: .
    environment:
    # mongodb://localhost/ballers
      - mongoConnectionString=mongodb://mongo:27017/ballers
    ports:
    - "8000:8000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"





