version: "3.8"
services:
  web:
    build: .
    environment:
    # mongodb://localhost/ballers
      - mongoConnectionString=mongodb://mongo:27017/ballers
    ports:
    - "8001:8001"
    volumes:
    - .:/usr/src/app
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27019:27017"





