version: "3.8"
services:
  web:
    build: .
    restart: unless-stopped
    env_file: "./config/development.js"
    environment:
    # mongodb://localhost/ballers
      - DOCKER_URL="mongodb://mongo:27017/ballers"
    ports:
    - "8001:8001"
    volumes:
    - .:/usr/src/app
    - node_modules:/usr/src/app/node_modules

    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27019:27017"





