version: "3.8"
services:
  web:
    build: .
    environment:
    # mongodb://localhost/ballers
      - mongoConnectionString=mongodb://mongo:27018/ballers
    ports:
    - "8001:8001"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27018:27017"





